
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 5/13/2020 11:55:25 PM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
#include <gb/drawing.h>

#include "my_lib01.h"
#include "Map_SplashScreen.h"

#define SPRITE_MIRROR   0x20

#define SCREENH_TILE    18
#define SCREENW_TILE    20
#define SCREENW_TILE_TOTAL    32

UINT8 dynMap[SCREENW_TILE_TOTAL * SCREENH_TILE];


inline void addPipeBottom (UINT8 x, UINT8 y){
    dynMap[x + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_1;
    dynMap[x+1 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_2;
    dynMap[x+2 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_3;


    for (y++; y < SCREENH_TILE-1; y++){
        dynMap[x + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_4;
        dynMap[x+1 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_5;
        dynMap[x+2 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_6;                
    }

}

inline void addPipeTop (UINT8 x, UINT8 y){
    dynMap[x + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_1;
    dynMap[x+1 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_2;
    dynMap[x+2 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_3;


    for (y--; y != 255; y--){
        dynMap[x + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_4;
        dynMap[x+1 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_5;
        dynMap[x+2 + y * SCREENW_TILE_TOTAL] = TILE_TUYAUX_6;                
    }

}


inline void drawSpriteBg(UINT8 topleftTile, UINT8 x, UINT8 y){
    dynMap[x + y * SCREENW_TILE_TOTAL] = topleftTile;
    dynMap[x + (y+1) * SCREENW_TILE_TOTAL] = topleftTile+1;
    dynMap[(x+1) + y * SCREENW_TILE_TOTAL] = topleftTile+2;
    dynMap[(x+1) + (y+1) * SCREENW_TILE_TOTAL] = topleftTile+3;
}

inline void makeGhostSprite(){
    //create the character ghost sprite
    set_sprite_tile(2, TILE_GHOST_A_NE);
    set_sprite_tile(3, TILE_GHOST_A_NW);
    set_sprite_prop(2, SPRITE_MIRROR);
    set_sprite_prop(3, SPRITE_MIRROR);


    move_sprite (2, 100, 70);
    move_sprite (3, 100+8, 70);
}

inline void autoscroller(){
    //fill blank
    for (UINT8 x = 0; x < SCREENW_TILE_TOTAL; x++){
        for (UINT8 y = 0; y < SCREENH_TILE; y++){
            dynMap[x + y * SCREENW_TILE_TOTAL] = TILE_EMPTY;
        }
    }

    //ground
    for (UINT8 x = 0; x < SCREENW_TILE_TOTAL; x++){
        if ((x & 0x01) == 0)
            dynMap[(SCREENH_TILE -1) * SCREENW_TILE_TOTAL + x] = TILE_GROUND1;
        else
            dynMap[(SCREENH_TILE -1) * SCREENW_TILE_TOTAL + x] = TILE_GROUND2;
    }

    //some bg decorations
    drawSpriteBg(TILE_BG_FLOWER_NW, 10, 10);
    drawSpriteBg(TILE_BG_STAR_NW, 14, 14);

    //make a pipe
    addPipeBottom (1, 14);
    addPipeTop (14, 6);

    //display
    set_bkg_tiles(0, 0, SCREENW_TILE_TOTAL, SCREENH_TILE, dynMap);

    makeGhostSprite();
    SHOW_SPRITES;

    //infinite game loop
    while (1){

        if(joypad() & J_DOWN) {
            scroll_sprite(2, 0, 1);
            scroll_sprite(3, 0, 1);
        }
        if(joypad() & J_UP) {
            scroll_sprite(2, 0, -1);
            scroll_sprite(3, 0, -1);
        }

        scroll_bkg(1, 0);

        wait_vbl_done();
    }
}




void main() {
    
    SPRITES_8x16;

    set_sprite_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_tiles(0, 0, Map_SplashScreen_WIDTH, Map_SplashScreen_HEIGHT, Map_SplashScreen);


    SHOW_BKG;
    SHOW_SPRITES;

    wait_vbl_done();

    while (1) {



        if(joypad() & J_START) {
            autoscroller();
        }

        wait_vbl_done();

    }
}


