
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 5/13/2020 11:55:25 PM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
#include <gb/drawing.h>

#include "my_lib01.h"

#include "game.h"


void main() {
    //stick to bank 0 for GB DMG compatibility
    VBK_REG = 0;

    SPRITES_8x16;

    set_sprite_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);
    set_win_data(0, my_lib01_COUNT, my_lib01);

    //load palettes
    set_bkg_palette (0, PALETTE_COUNT, bgPalette);
    set_sprite_palette (0, PALETTE_COUNT, bgPalette);
    

    SHOW_BKG;
    SHOW_SPRITES;

    
    wait_vbl_done();

    while (1) {



        autoscroller();

        wait_vbl_done();

    }
}


