
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 6/2/2020 10:40:39 PM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
#include <gb/drawing.h>

#include "my_lib01.h"
#include "Map_Screen1.h"

void main() {
    SPRITES_8x8;

    set_sprite_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_tiles(0, 0, Map_Screen1_WIDTH, Map_Screen1_HEIGHT, Map_Screen1);

    SHOW_BKG;
    SHOW_SPRITES;

    wait_vbl_done();

    while (1) {
        wait_vbl_done();

    }
}


