
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 6/2/2020 10:40:39 PM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
//#include <gb/cgb.h>
#include <gb/drawing.h>

#include "my_lib01.h"
#include "Map_Screen1.h"
#include "Export.h"

#define PALETTE_COUNT   4
UWORD bgPalette[] = {
	RGB_WHITE, RGB_RED, RGB_ORANGE, RGB_YELLOW,
	0, RGB_GREEN, RGB_BLUE, RGB_PURPLE,
	0, RGB_BLACK, RGB_DARKGRAY, RGB_WHITE,
	0, RGB_YELLOW, RGB_DARKBLUE, RGB_PINK
};

void main() {
    UINT8 X,Y, SPRITE_FRAME ;
    INT8 dx, dy;

    SPRITES_8x8;

    set_sprite_data(0, my_lib01_COUNT, TileLabel);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_tiles(0, 0, Map_Screen1_WIDTH, Map_Screen1_HEIGHT, Map_Screen1);

    SHOW_BKG;
    SHOW_SPRITES;

    //stick to bank 0 for GB DMG compatibility
    VBK_REG = 0;

    //load palettes
    //set_bkg_palette (0, PALETTE_COUNT, bgPalette);
    //set_sprite_palette (0, PALETTE_COUNT, bgPalette);

    X = 50;
    Y = 50;
    dx = 1;
    dy = 1;

    SPRITE_FRAME=0;

    set_sprite_tile(0, SPRITE_FRAME);
    move_sprite(0, X, Y);
    //assign palette to sprites
    //set_sprite_prop(0, 0x01U);

    wait_vbl_done();

    UINT8 spal = 1;

    while (1) {
        wait_vbl_done();
        if (joypad() & J_UP){
            dy--;
        }
        if (joypad() & J_DOWN){
            dy++;
        }
        if (joypad() & J_LEFT){
            dx--;
        }
        if (joypad() & J_RIGHT){
            dx++;
        }
        if (joypad() & J_A){
            //palette change
            set_sprite_prop(0, spal);
            spal++;
            spal = spal % PALETTE_COUNT;
        }

        X = X + dx;
        Y = Y + dy;

        //TODO: fix this it's copy pasted from other project that was for 16x16 sprites
        //X is the MIDDLE of the 16x16 sprite
        if (X <= (8+8) || X >= ((20-1) * 8 -8) )
            dx=-dx;

        //Y is the BOTTOM of the 16x16 sprite
        if (Y <= (8+16) || Y >= ((18-1) *8) )
            dy=-dy;

        move_sprite(0, X, Y);

        SPRITE_FRAME = (SPRITE_FRAME + 1) % 4;
        set_sprite_tile(0, SPRITE_FRAME);
        delay(50);
    }
}


