
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 3/21/2020 8:44:00 AM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
#include <gb/drawing.h>

#include "my_lib01.c"
#include "Map_Intro.h"
#include "Map_Room1.h"

#define MV_HERO(x,y) move_sprite(0, x, y); move_sprite(1, x+8, y);


void main() {
  int x = 50;
  int y = 50;
  
    SPRITES_8x16;

    set_sprite_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);

    set_bkg_tiles(0, 0, Map_Intro_WIDTH, Map_Intro_HEIGHT, Map_Intro);

    set_sprite_tile(0, TILE_HERO_NW);
    set_sprite_tile(1, TILE_HERO_NE);
    
    MV_HERO(x, y);
    
    SHOW_BKG;
    SHOW_SPRITES;

    wait_vbl_done();


    while(1) {
        if(joypad() & J_RIGHT) {
            x++;
            MV_HERO(x, y);
            delay(10);
        }
        if(joypad() & J_LEFT) {
            x--;
            MV_HERO(x, y);
            delay(10);
        }
        if(joypad() & J_UP) {
            y--;
            MV_HERO(x, y);
            delay(10);
        }
        if(joypad() & J_DOWN) {
            y++;
            MV_HERO(x, y);
            delay(10);
        }

	wait_vbl_done();
    }
}


