
/*************************
**
** Autogenerated stub for basic program that just displays the first Map.
** Made by GbReaper at 3/21/2020 8:44:00 AM
** AlanFromJapan - https://electrogeek.cc
**
*/

#include <gb/gb.h>
#include <gb/drawing.h>

#include "my_lib01.c"
#include "Map_Intro.h"
#include "Map_Room1.h"

#define SCREENW         160
#define SCREENH         144
#define HSCROLLLEFT     32
#define HSCROLLRIGHT    128


#define MV_HERO(x,y) move_sprite(0, x, y); move_sprite(1, x+8, y);
unsigned int x = 50;
unsigned int y = 50;

unsigned int bgx = 0;
unsigned int bgy = 0;

unsigned int lastJoypad = 0;

unsigned int currentMapW = SCREENW;

/**
 * Vertical blank interrupt: where we "draw" memory while screen is not updated
 */
void vblint(){
    SCX_REG = bgx;

    MV_HERO(x, y);
}

/**
 * MAIN method
 */
void main() {
  
    SPRITES_8x16;

    set_sprite_data(0, my_lib01_COUNT, my_lib01);
    set_bkg_data(0, my_lib01_COUNT, my_lib01);

    set_bkg_tiles(bgx, bgy, Map_Intro_WIDTH, Map_Intro_HEIGHT, Map_Intro);
    currentMapW = Map_Intro_WIDTH * 8;

    set_sprite_tile(0, TILE_HERO_NW);
    set_sprite_tile(1, TILE_HERO_NE);
    
    MV_HERO(x, y);
    
    SHOW_BKG;
    SHOW_SPRITES;

    wait_vbl_done();
    //branch interrup handler for VBlank
    add_VBL(vblint);

    while(1) {
        lastJoypad = joypad();
        if(lastJoypad & J_RIGHT && x < SCREENW-8) {
            x++;
        }
        if(lastJoypad & J_LEFT && x > 8) {
            x--;
        }
        if(lastJoypad & J_UP && y > 16) {
            y--;
        }
        if(lastJoypad & J_DOWN && y < SCREENH) {
            y++;
        }


        //move bg Left ? only on big maps
        if (currentMapW > SCREENW && bgx < (currentMapW - SCREENW) &&  x > HSCROLLRIGHT) {
            x--;
            bgx ++;

        }
        /*
        else {
            //move bg Right ? only on big maps
            if (currentMapW > SCREENW && bgx > 0  &&  x < HSCROLLRIGHT) {
                x++;
                bgx --;
                SCX_REG = bgx;
            }
        }
        */


        //debouncing on the cheap
        delay(10);
    }
}


