
#ifndef __my_lib01_H__
#define __my_lib01_H__

#define my_lib01_COUNT   188


#define TILE_SAPIN_NW   0
#define TILE_SAPIN_SW   1
#define TILE_SAPIN_NE   2
#define TILE_SAPIN_SE   3
#define TILE_PALMTREE_NW   4
#define TILE_PALMTREE_SW   5
#define TILE_PALMTREE_NE   6
#define TILE_PALMTREE_SE   7
#define TILE_TOWER_1   8
#define TILE_TOWER_2   9
#define TILE_TOWER_3   10
#define TILE_TOWER_4   11
#define TILE_TOWER_5   12
#define TILE_ROCK_NW   13
#define TILE_ROCK_SW   14
#define TILE_ROCK_NE   15
#define TILE_ROCK_SE   16
#define TILE_COLUMN_NW   17
#define TILE_COLUMN_SW   18
#define TILE_COLUMN_NE   19
#define TILE_COLUMN_SE   20
#define TILE_EMPTY   21
#define TILE_COFFRE_NW   22
#define TILE_COFFRE_SW   23
#define TILE_COFFRE_NE   24
#define TILE_COFFRE_SE   25
#define TILE_DOOR_NW   26
#define TILE_DOOR_SW   27
#define TILE_DOOR_NE   28
#define TILE_DOOR_SE   29
#define TILE_PENTAGRAM_NW   30
#define TILE_PENTAGRAM_SW   31
#define TILE_PENTAGRAM_NE   32
#define TILE_PENTAGRAM_SE   33
#define TILE_STAIRS_UP_NW   34
#define TILE_STAIRS_UP_SW   35
#define TILE_STAIRS_UP_NE   36
#define TILE_STAIRS_UP_SE   37
#define TILE_TABLE_NW   38
#define TILE_TABLE_SW   39
#define TILE_TABLE_NE   40
#define TILE_TABLE_SE   41
#define TILE_STAIRS_DOWN_NW   42
#define TILE_STAIRS_DOWN_SW   43
#define TILE_STAIRS_DOWN_NE   44
#define TILE_STAIRS_DOWN_SE   45
#define TILE_MARBLE_STELE_NW   46
#define TILE_MARBLE_STELE_SW   47
#define TILE_MARBLE_STELE_NE   48
#define TILE_MARBLE_STELE_SE   49
#define TILE_WEAPON_WALL_NW   50
#define TILE_WEAPON_WALL_SW   51
#define TILE_WEAPON_WALL_NE   52
#define TILE_WEAPON_WALL_SE   53
#define TILE_TORCH_NW   54
#define TILE_TORCH_SW   55
#define TILE_TORCH_NE   56
#define TILE_TORCH_SE   57
#define TILE_SKELETON_NW   58
#define TILE_SKELETON_SW   59
#define TILE_SKELETON_NE   60
#define TILE_SKELETON_SE   61
#define TILE_WMAGE_NW   62
#define TILE_WMAGE_SW   63
#define TILE_WMAGE_NE   64
#define TILE_WMAGE_SE   65
#define TILE_GIRL_NW   66
#define TILE_GIRL_SW   67
#define TILE_GIRL_NE   68
#define TILE_GIRL_SE   69
#define TILE_DWARF_NW   70
#define TILE_DWARF_SW   71
#define TILE_DWARF_NE   72
#define TILE_DWARF_SE   73
#define TILE_CRANE_NW   74
#define TILE_CRANE_SW   75
#define TILE_CRANE_NE   76
#define TILE_CRANE_SE   77
#define TILE_FIRE_NW   78
#define TILE_FIRE_SW   79
#define TILE_FIRE_NE   80
#define TILE_FIRE_SE   81
#define TILE_SNOWMAN_NW   82
#define TILE_SNOWMAN_SW   83
#define TILE_SNOWMAN_NE   84
#define TILE_SNOWMAN_SE   85
#define TILE_BIGTILE_NW   86
#define TILE_BIGTILE_SW   87
#define TILE_BIGTILE_NE   88
#define TILE_BIGTILE_SE   89
#define TILE_GROUND1_NW   90
#define TILE_GROUND1_SW   91
#define TILE_GROUND1_NE   92
#define TILE_GROUND1_SE   93
#define TILE_CRYSTAL_NW   94
#define TILE_CRYSTAL_SW   95
#define TILE_CRYSTAL_NE   96
#define TILE_CRYSTAL_SE   97
#define TILE_REMAINS_NW   98
#define TILE_REMAINS_SW   99
#define TILE_REMAINS_NE   100
#define TILE_REMAINS_SE   101
#define TILE_SNAKE_NW   102
#define TILE_SNAKE_SW   103
#define TILE_SNAKE_NE   104
#define TILE_SNAKE_SE   105
#define TILE_HERO_NW   106
#define TILE_HERO_SW   107
#define TILE_HERO_NE   108
#define TILE_HERO_SE   109
#define TILE_HERO2_NW   110
#define TILE_HERO2_SW   111
#define TILE_HERO2_NE   112
#define TILE_HERO2_SE   113
#define TILE_HERO_UP_NW   114
#define TILE_HERO_UP_SW   115
#define TILE_HERO_UP_NE   116
#define TILE_HERO_UP_SE   117
#define TILE_HERO_UP_2_NW   118
#define TILE_HERO_UP_2_SW   119
#define TILE_HERO_UP_2_NE   120
#define TILE_HERO_UP_2_SE   121
#define TILE_HERO_LEFT_NW   122
#define TILE_HERO_LEFT_SW   123
#define TILE_HERO_LEFT_NE   124
#define TILE_HERO_LEFT_SE   125
#define TILE_HERO_LEFT_2_NW   126
#define TILE_HERO_LEFT_2_SW   127
#define TILE_HERO_LEFT_2_NE   128
#define TILE_HERO_LEFT_2_SE   129
#define TILE_GRASS_1   130
#define TILE_GRASS_2   131
#define TILE_SAND   132
#define TILE_WINDOW_1   133
#define TILE_WINDOW_2   134
#define TILE_WINDOW_3   135
#define TILE_WINDOW_4   136
#define TILE_WINDOW_5   137
#define TILE_WINDOW_6   138
#define TILE_WINDOW_7   139
#define TILE_WINDOW_8   140
#define TILE_LETTER_1   141
#define TILE_LETTER_2   142
#define TILE_LETTER_3   143
#define TILE_LETTER_4   144
#define TILE_LETTER_5   145
#define TILE_LETTER_6   146
#define TILE_LETTER_7   147
#define TILE_LETTER_8   148
#define TILE_LETTER_9   149
#define TILE_LETTER_10   150
#define TILE_LETTER_11   151
#define TILE_LETTER_12   152
#define TILE_LETTER_13   153
#define TILE_LETTER_14   154
#define TILE_LETTER_15   155
#define TILE_LETTER_16   156
#define TILE_LETTER_17   157
#define TILE_LETTER_18   158
#define TILE_LETTER_19   159
#define TILE_LETTER_20   160
#define TILE_LETTER_21   161
#define TILE_LETTER_22   162
#define TILE_LETTER_23   163
#define TILE_LETTER_24   164
#define TILE_LETTER_25   165
#define TILE_LETTER_26   166
#define TILE_LETTER_COMMA   167
#define TILE_LETTER_DOT   168
#define TILE_LETTER_EXCL   169
#define TILE_LETTER_QUESTION   170
#define TILE_CLE   171
#define TILE_POTION   172
#define TILE_BONBON   173
#define TILE_BOURSE   174
#define TILE_NUMBER_1   175
#define TILE_NUMBER_2   176
#define TILE_NUMBER_3   177
#define TILE_NUMBER_4   178
#define TILE_NUMBER_5   179
#define TILE_NUMBER_6   180
#define TILE_NUMBER_7   181
#define TILE_NUMBER_8   182
#define TILE_NUMBER_9   183
#define TILE_NUMBER_10   184
#define TILE_HEART_0   185
#define TILE_HEART_HALF   186
#define TILE_HEART_FULL   187


//declared as const to save compile and execution time/space
extern const unsigned char my_lib01[]; 

#endif //__my_lib01_H__


